#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const envTemplate = `# Mementic Environment Configuration
# This file was generated by setup-env.js
# Canister IDs are now automatically loaded from declaration files

# Internet Identity Configuration
VITE_INTERNET_IDENTITY_HOST=https://identity.ic0.app

# Development Mode (set to true for local development)
VITE_DEV_MODE=true

# Agent Host (usually https://icp-api.io for production, http://127.0.0.1:4943 for local)
VITE_AGENT_HOST=https://icp-api.io

# Feature Flags
VITE_ENABLE_MEME_GENERATION=true
VITE_ENABLE_VOTING=true
VITE_ENABLE_NFT_MINTING=true

# API Configuration
VITE_REQUEST_TIMEOUT=30000
VITE_MAX_RETRIES=3
`;

const rootDir = __dirname;
const envPath = path.join(rootDir, ".env");

console.log("🚀 Setting up Mementic environment configuration...");

// Check if .env already exists
if (fs.existsSync(envPath)) {
  console.log("⚠️  .env file already exists in the root directory");
  console.log("   Please update it manually if needed.");
} else {
  // Create .env file
  fs.writeFileSync(envPath, envTemplate);
  console.log("✅ Created .env file in the root directory");
}

console.log("\n📋 Next steps:");
console.log("1. Deploy your backend: dfx deploy Mementic_backend");
console.log("2. Generate declarations: dfx generate Mementic_backend");
console.log("3. Start the frontend: cd src/Mementic_frontend && npm run dev");
console.log(
  "\n💡 Note: Canister IDs are now automatically loaded from declaration files!"
);
